### ISSUE TITLE
Haxe 4.3 documentation TODO

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/HaxeManual#524]
* [x] defaults for type parameters (HaxeFoundation/haxe#10518)
* [x] support abstract keyword to reference the abstract (HaxeFoundation/haxe#10513)
* [x] support static var at expression-level (HaxeFoundation/haxe#10555)
* [x] support ?. safe navigation operator (HaxeFoundation/haxe#10561)
* [x] added ?? null coalescing operator (HaxeFoundation/haxe#10428)
* [ ] add -w compiler option to configure warnings (HaxeFoundation/haxe#10612)
* [x] support custom metadata and defines (HaxeFoundation/haxe#10858)

**Comment by EliteMasterEric** [comment]
I ended up writing this blog post which covers all of these features: https://www.elitemastereric.com/Haxe-430/

I sadly don't have the time to help out by copying parts of this over and cleaning them up (this post alone took several hours and I haven't made dinner), but anyone working on improving the official documentation can feel free to copy and use this post or portions of it in there.

**Comment by RblSb** [comment]
You can add link to https://haxe.org/download/, update already on this page

**Comment by Simn** [comment]
That is great content, thank you! I'll see to it that we add a link to it from the release notes.

Regarding `-w`, I decided to not use any numeric codes because I don't see any reason to do so. Every warning has its unique identifier, which is printed alongside the warning. So you can always just `-w -WIdentifier` to immediately deal with it. We will probably generate a list from this JSON source: https://github.com/HaxeFoundation/haxe/blob/development/src-json/warning.json

**Comment by kLabz** [comment]
Thank you for your blog post, that will help the community while we work on writing (and deploying...) the documentation about new things, "breaking fixes" , etc.

While I go through all that to work on new pages, I can point out things that are a bit incorrect if you want to edit your post. From what I remember from my first "quick" read it's mostly correct, so there won't be much. Maybe you want to fix that "type safety" at the end that is supposed to be "null safety" , if that's not fixed already.

**Comment by kLabz** [comment]
- [ ] Update macro reification page to add something about the 4.3 change too?
